train_path = "data/trainset/train.simple.json"
eval_path = "data/devset/dev.simple.json"
track = "simple"
prompt = "simple/examples"

model = "3.0/gpt_bert/cls"
max_length = 16384

epochs = 2
lr = 2e-5
train_batch_size = 2

batch_size = 4
device = "cuda"
output_dir = "results"
