train_path = "data/translated/train.rubric.json"
eval_path = "data/translated/dev.rubric.json"
track = "rubric"
prompt = "rubric/zero_shot"

model = "3.0/gpt_bert/cls"
max_length = 16384

epochs = 2
lr = 2e-5
train_batch_size = 2

batch_size = 4
device = "cuda"
output_dir = "results"
